[telescope]
TelescopeDiameter = 8.05
ObscurationRatio = 0.314
PathPupil = 'Examples/Configuration/pupil.daytime.215p.fits'

[atmosphere]
Wavelength = 500e-9
L0 = 40.0

[sources_science]

[sources_HO]
Wavelength = 750e-9
Height = 0.0

[sensor_science]
; may not correct
PixelScale = 14.95
FieldOfView = 200

[sensor_HO]
WfsType = 'Pyramid'
NumberLenslets = [40]
PixelScale = 1050
FieldOfView = 2
Modulation = 3
Binning = 2
; get from header
ExcessNoiseFactor = 1.41421356237
SigmaRON = 0.5

[DM]
NumberActuators = [30]
DmPitchs = [0.275]
DmHeights = [0.0]
AoArea = 'circle'


[RTC]
; Those have to be dependent on the data aquisition
LoopGain_HO = 0.13
;SensorFrameRate_HO = 1700.0
; a 1100Hz -> 2.5ms
LoopDelaySteps_HO = 2.5 

[COMPUTATION]
precision = 'single'
